- name: Include user and group creation
  import_tasks: user_group.yml

- name: Include directories creation
  import_tasks: directories.yml

- name: Include download and install of Consul
  import_tasks: install.yml
