- name: Include user and group creation
  import_tasks: user_group.yml

- name: Include directories creation
  import_tasks: directories.yml

- name: Include download and install of Consul
  import_tasks: install.yml

- name: Set configuration
  import_tasks: configuration.yml

- name: Start service
  import_tasks: service.yml
